spring:
  application:
    name: academic-system

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  
  mvc:
    static-path-pattern: /**

# JWT配置
jwt:
  secret: ${JWT_SECRET:university-academic-system-secret-key-2024}
  expiration: 86400000  # 24小时（毫秒）
  refresh-expiration: 604800000  # 7天（毫秒）

# 学术系统业务规则配置
academic:
  rules:
    max-credits-per-semester: 30  # 每学期最大学分
    max-courses-per-semester: 8   # 每学期最多课程数
    drop-deadline-days: 14        # 退课截止天数
    login-failure-limit: 3        # 登录失败次数限制
    account-lock-minutes: 15      # 账户锁定时间（分钟）

# 日志配置
logging:
  level:
    root: INFO
    com.university.academic: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false

